version: '3'

services:

  db:

    env_file: .env
    image: postgres:16
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  bot:
    env_file: .env
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db